// Maps all known birth place text to canonical keys
export const BirthPlaceText = new Map([
['', 'Missing'],
["'s-Gravendeel, South Holland, Netherlands", "NET, ZUI, 's-Gravendeel"],
["'s-Gravendeel,Zuid Holland,Nederland",  "NET, ZUI, 's-Gravendeel"],
['Aalsmeer, North Holland, Netherlands', 'NET, NOR, Aalsmeer'],
['Aalten, Netherlands', 'NET, GEL, Aalten'],
['Acadia (Nova Scotia & New Brunswick), Canada', 'CAN, NB, Acadia'],
['Accomack, Virginia, USA', 'USA, VA, Accomack'],
['Alveley, Shropshire, England', 'ENG, SAL, Alvely'],
['An Glan, Zweibrucken, Rhineland-Palatinate, Allemagne', 'GER, RP, Zweibrucken, An Glan'],
['Anne Arundel County, Maryland, United States of America', 'USA, MD, Anne Arundel'],
['Anne Arundel, Baltimore, Maryland, USA', 'USA, MD, Anne Arundel, Baltimore'],
['Anne Arundel, British Colonial America, Maryland, USA', 'USA, MD, Anne Arundel'],
['Anne Arundel, Maryland, United States', 'USA, MD, Anne Arundel'],
['Armagh, Northern Ireland', 'NIR, ARM'],
['Ashford, Windham, Connecticut, USA', 'USA, CT, Windham, Ashford'],
['Aston Flamville, Leicestershire, England', 'ENG, LEI, Aston Flamville'],
['Atwood, Kosciusko, Indiana, USA', 'USA, IN, Kosciusko, Atwood'],
['Augusta County, Virginia, USA', 'USA, VA, Augusta'],
['Baie-St-Paul, Charlevoix, Quebec, Canada', 'CAN, QC, Charlevoix, Baie-St-Paul'],
// ['Bakke farm, S├╕r-Aurdal, Oppland, Norv├¿ge', 'NOR, OPP, S├╕r-Aurdal, Bakke farm'],
['Bakke farm, Sør-Aurdal, Oppland, Norvège', 'NOR, OPP, Sør-Aurdal, Bakke farm'],
['Baltimore City, Maryland, USA', 'USA, MD, Baltimore'],
['Baltimore, Baltimore, Maryland, USA', 'USA, MD, Baltimore'],
['Baltimore, Baltimore, Maryland, United States', 'USA, MD, Baltimore'],
['Baltimore, Maryland, USA', 'USA, MD, Baltimore'],
['Bammental, Rhein-Neckar-Kreis, Baden-Wuerttemberg, Germany', 'GER, BW, Rhein-Neckar-Kreis, Bammental'],
['Barrington, Bristol County, Rhode Island, USA', 'USA, RI, Bristol, Barrington'],
['Barwell, Leicestershire, England', 'ENG, LEI, Barwell'],
['Bath, Augusta County, Virginia, USA', 'USA, VA, Augusta, Bath'],
// ['Berthier, (Sainte-Genevi├¿ve), (Berthier), Qu├⌐bec, Canada', 'CAN, QC, Berthier, Sainte-Genevi├¿ve'],
['Berthier, (Sainte-Geneviève), (Berthier), Québec, Canada', 'CAN, QC, Berthier, Sainte-Geneviève'],
// ['Berthier, (Sainte-Genevi├¿ve), (Berthier), Qu├⌐bec, Canada', 'CAN, QC, Berthier, Sainte-Genevi├¿ve'],
// ['Bj├╕rnebyqvern, ├àsnes, Hedmark, Norv├¿ge', 'NOR, HED, ├àsnes, Bj├╕rnebyqvern'],
['Bjørnebyqvern, Åsnes, Hedmark, Norvège', 'NOR, HED, Åsnes, Bjørnebyqvern'],
['Blackclough, Stanhope, Durham, England', 'ENG, DUR, Stanhope, Blackclough'],
['Bland, Bland, Virginia, USA', 'USA, VA, Bland, Bland'],
['Botetourt, Virginia, United States', 'USA, VA, Botetourt'],
['Bristol, Rhode Island, USA', 'USA, RI, Bristol'],
['Bristol, Somerset, England', 'ENG, SOM, Bristol'],
['Brixham, Devon, England', 'ENG, DEV, Brixham'],
['Brixham, Devon,  England', 'ENG, DEV, Brixham'],
['Brixham, Devon, England, United Kingdom', 'ENG, DEV, Brixham'],
['Brixham, Devonshire, England', 'ENG, DEV, Brixham'],
['Brixham,Devon,England', 'ENG, DEV, Brixham'],
['Broadwood, Stanhope, Durham, England', 'ENG, DUR, Stanhope, Broadwood'],
['Buckingham, Buckingham, Virginia, USA', 'USA, VA, Buckingham, Buckingham'],
['Buckinghamshire, England', 'ENG, BKM'],
// ['B├ñnkeboda, ├älmeboda, Kronoberg, Sverige', 'SWE, KRO, ├älmeboda, B├ñnkeboda'],
['Bänkeboda, Älmeboda, Kronoberg, Sverige', 'SWE, KRO,  Älmeboda, Bänkeboda'],
['Calvert Cliffs, Calvert, Maryland, USA', 'USA, MD, Calvert, Calvert Cliffs'],
['Cambridge, Cambridgeshire, England', 'ENG, CAM, Cambridge'],
['Carrickmacross, Monaghan, Ireland', 'IRE, MOG, Carrickmacross'],
['Carrol County, Indiana, USA', 'USA, IN, Carroll'],
['Carroll County, Indiana', 'USA, IN, Carroll'],
['Carroll County, Maryland, United States of America', 'USA, MD, Carroll'],
['Cass County, Indiana, United States of America', 'USA, IN, Cass'],
['Cass, Indiana, USA', 'USA, IN, Cass'],
['Cavan, Peterborough County, Ontario, Canada', 'CAN, ON, Peterborough, Cavan'],
['Cayuga County, New York, United States of America', 'USA, NY, Cayuga'],
['Charles County, Maryland, USA', 'USA, MD, Charles'],
['Charlois, Rotterdam, Zuid-Holland, Netherlands', 'NET, ZUI, Rotterdam, Charlois'],
['Chealiston, Devon, England', 'ENG, DEV, Chealiston'],
['Cheshire, Cheshire, England', 'ENG, CHS, Cheshire'],
['Chester County, Pennsylvania, USA', 'USA, PN, Chester'],
['Chester County, Pennsylvania, United States of America', 'USA, PN, Chester'],
['Chester, Pennsylvania, USA', 'USA, PN, Chester'],
['Chesterfield, Chesterfield, Virginia, USA', 'USA, VA, Chesterfield'],
['Chesterfield, Virginia, USA', 'USA, VA, Chesterfield'],
['Clinton, Clinton, New York, USA', 'USA, NY, Clinton, Clinton'],   // But Clinton is in Oneida County?
['Clotts Farm, Stanton under Bardon, Leicestershire, England', 'ENG, LEI, Stanton under Bardon, Clotts Farm'],
['Coffey, Kansas, USA', 'USA, KS, Coffey'],
['Colfax, Jasper County (US/IA)', 'USA, IA, Jasper, Colfax'],
['Comber, Down County, Ulster, Ireland', 'NIR, DOW, Comber'],
['Connecticut, USA', 'USA, CT'],
['Cork, Cork, Ireland', 'IRE, COR, Cork'],
['Cork, Ireland', 'IRE, COR'],
['County Down, Ulster, Ireland', 'NIR, DOW'],
['County Durham, England', 'ENG, DUR'],
['Coventry, Warwickshire, England', 'ENG, WAR, Coventry'],
['Darke County, Ohio, United States', 'USA, OH, Darke'],
['Dartmouth, Devon, England', 'ENG, DEV, Dartmouth'],
['Deer River, Itasca, Minnesota, USA', 'USA, MN, Itasca, Deer River'],
['Donegal, Donegal, Ulster, Ireland', 'NIR, DON, Donegal'],
['Donegal, Donegal, Ulster, Ireland', 'NIR, DON, Donegal'],
['Donnahlong, Down, Ulster, Ireland', 'NIR, DOW, Donnahlong'],
['Dunmanway, Cork, Ireland', 'IRE, COR, Dunmanway'],
['Durham County, England', 'ENG, DUR'],
['Earl Shilton, Leicestershire, England', 'ENG, LEI, Earl Shilton'],
['Earsdon,Tynemouth, Northumberland, England', 'ENG, NBL, Tynemouth, Earsdon'],
['Easington Parish, Yorkshire, England', 'ENG, YKS, Easington'],
['Easington, Yorkshire, England', 'ENG, YKS, Easington'],
['Easington, Yorkshire, England,', 'ENG, YKS, Easington'],
['Eastcott, North, Hamptonshire, England', 'ENG, NOR, Eastcott'],
['Ekoupag Meductic, Saint John River, New Brunswick, Canada', 'CAN, NB, Acadia, Saint John River, Meductic'],
['England', 'ENG'],
['Fauquier County, Virginia, USA', 'USA, VA, Fauquier'],
['Fauquier, Virginia, USA', 'USA, VA, Fauquier'],
['Franklin County, Pennsylvania, United States of America', 'USA, PN, Franklin'],
['Franklin, Virginia, USA', 'USA, VA, Franklin'],
['Frederick City, MD, Maryland, USA', 'USA, MD, Frederick, Frederick'],
['Frederick County, Maryland, USA', 'USA, MD, Frederick'],
['Frederick, Baltimore County, Colonial America, Maryland, USA', 'USA, MD, Frederick, Frederick'],
['Frederick, Frederick, Maryland, USA', 'USA, MD, Frederick, Frederick'],
['Frederick, Maryland, United States', 'USA, MD, Frederick'],
['Fredericksburg, Spotsylvania, Virginia, United States', 'USA, VA, Spotsylvania, Fredericksburg'],
['Fredericksburg, Virginia, USA', 'USA, VA, Spotsylvania, Fredericksburg'],
['Gateshead, Durham,England', 'ENG, DUR, Gateshead'],
['Germany, Allemagne', 'GER'],
['Germany, Baden-Wuerttemberg, Germany', 'GER, BW'],
['Glasgow, Lanarkshire, Scotland', 'SCO, LKS, Glasgow'],
['Gloucester, Essex, Massachusetts, United States', 'USA, MA, Essex, Gloucester'],
['Goochland, Goochland, Virginia, USA', 'USA, VA, Goochland, Goochland'],
['Goudswaard, Korendijk, Zuid-Holland, Netherlands', 'NET, ZUI, Korendijk, Goudswaard'],
['Grand Rapids, Itasca, MN, USA', 'USA, MN, Itasca, Grand Rapids'],
['Greene, Pennsylvania, USA', 'USA, PN, Greene'],
['Halifax, Virginia, USA', 'USA, VA, Halifax'],
['Halls End, Warwickshire, England', 'ENG, WAR, Halls End'],
['Hanover County, Virginia, United States of America', 'USA, VA, Hanover'],
['Hanover, Virginia, United States', 'USA, VA, Hanover'],
['Harford County, Maryland, USA', 'USA, MD, Harford'],
['Harrison Co, Ohio, USA', 'USA, OH, Harrison'],
['Harrison County, Ohio, USA', 'USA, OH, Harrison'],
['Harrison, Ohio, United States', 'USA, OH, Harrison'],
['Hedalen, Sor Aurdal, Oppland, Norway', 'NOR, OPP, Sør-Aurdal, Hedalen'],
['Henry, Illinois, USA', 'USA, IL, Henry'],
['Heyworth, Durham, England', 'ENG, DUR, Heyworth'],
['Hicksford, Greensville, Virginia, USA', 'USA, VA, Greensville, Hicksford'],
['Hoosick Falls, Rensselaer County, New York, United States of America', 'USA, NY, Rensselaer, Hoosick Falls'],
['Hoosick, Rensselaer, New York, USA', 'USA, NY, Rensselaer, Hoosick'],
['Ibstock, Leicestershire, England', 'ENG, LEI, Ibstock'],
['Indiana, USA', 'USA, IN'],
['Island Lake, Rolette, North Dakota, USA', 'USA, ND, Rolette, Island Lake'],
['Jarrow, Durham, England', 'ENG, DUR, Jarrow'],
['Jefferson City, Ohio, USA', 'USA, OH, Ashtabula, Jefferson'],
["John's Creek, Floyd County, Kentucky, USA", "USA, KY, Floyd, John's Creek"],
['Johns Creek, Floyd, Kentucky, USA', "USA, KY, Floyd, John's Creek"],
['Johnson, Kentucky, USA', 'USA, KY, Johnson'],
['Joranbyhuset, Hedalen, Sor Aurdal, Oppland, Norway', 'NOR, OPP, Sør-Aurdal, Hedalen, Joranbyhuset'],
['Kennett Square, Chester, Pennsylvania, USA', 'USA, PN, Chester, Kennett Square'],
['Kennett Square, Chester, Pennsylvania, United States of America', 'USA, PN, Chester, Kennett Square'],
['Kent, England', 'ENG, KEN'],
['King William, King William, VA, Virginia, USA', 'USA, VA, King William, King William'],
['King William, King William, Virginia, United States', 'USA, VA, King William, King William'],
['Kingston, Meeker, Minnesota, USA', 'USA, MN, Meeker, Kingston'],
['Kingston, Wright, Minnesota, USA', 'USA, MN, Meeker, Kingston'],
['Kirkcudbrightshire, Scotland', 'SCO, KKD'],
['Kriegsfeld, Donnersberg, Rhineland-Palatinate, Germany', 'GER, RP, Donnersberg, Kriegsfeld'],
['Kromstrijen, Zuid-Holland, Netherlands', 'NET, ZUI, Kromstrijen'],
['Kronoberg, Orebro, Sweden', 'SWE, KRO, Orebro'],
// ["L'Assomption, (l'Assomption), Qu├⌐bec, Canada", "CAN, QC, L'Assomption"],
["L'Assomption, (l'Assomption), Québec, Canada", "CAN, QC, L'Assomption"],
// ["L'Isle-Verte (├ëglise Saint-Jean-Baptiste), 150, rue Saint-Jean-Baptiste, Qu├⌐bec, Canada", "CAN, QC, Bas-Saint-Laurent, L'Isle-Verte"],
["L'Isle-Verte (Église Saint-Jean-Baptiste), 150, rue Saint-Jean-Baptiste, Québec, Canada", "CAN, QC, Bas-Saint-Laurent, L'Isle-Verte"],
["L'Isle-Verte, Riviere-du-Loup, Quebec, Canada", 'CAN, QC, Bas-Saint-Laurent, Riviere-du-Loup'],
// ['La C├┤te-de-Gasp├⌐, Gaspesie-Iles-de-la-Madeleine Region, Quebec, Canada', 'CAN, QC, Gaspesie-Iles-de-la-Madeleine, La C├┤te-de-Gasp├⌐,'],
['La Côte-de-Gaspé, Gaspesie-Iles-de-la-Madeleine Region, Quebec, Canada', 'CAN, QC, Gaspesie-Iles-de-la-Madeleine, La C├┤te-de-Gasp├⌐,'],
['Lagrange, Lagrange, Indiana, USA', 'USA, IN, LaGrange'],
['Lancaster, Pennsylvania, USA', 'USA, PN, Lancaster'],
['Lee County, Virginia, USA', 'USA, VA, Lee'],
['Leicester, Leicestershire, England', 'ENG, LEI, Leicester'],
['Linlithgow, West Lothian, Linlithgowshire, Scotland', 'SCO, WLN, Linlithgow'],
// ['Linneryd fg, Tokam├Ñla, Kronoberg, Su├¿de', 'SWE, KRO, Tokam├Ñla, Linneryd fg'],
['Linneryd fg, Tokamåla, Kronoberg, Suède', 'SWE, KRO, Tokamåla, Linneryd fg'],
['Linneryd, Kronoberg, Sverige', 'SWE, KRO, Linneryd'],
['Linton Hundred, Washington, Maryland, United States', 'USA, MD, Washington, Linton Hundred'],
['London, England', 'ENG, LND'],
['Longueuil, Quebec, Canada', 'CAN, QC, Monteregie, Longueuil'],
['Lurgan, Shankill, Armagh, Northern Ireland', 'NIR, ARM, Skankill, Lurgan'],
['Maasdam, Binnenmaas, South Holland, Zuid-Holland, Pays-Bas', 'NET, ZUI, Maasdam'],
['Maasdam, Binnenmaas, Zuid-Holland, Netherlands', 'NET, ZUI, Maasdam'],
['Maasdam, Zuid Holland, Netherlands', 'NET, ZUI, Maasdam'],
['Maasdam, Zuid-Holland, Nl', 'NET, ZUI, Maasdam'],
['Maasdam, Zuid-Holland, Pays-Bas', 'NET, ZUI, Maasdam'],
['Macroom, Cork, Munster, Ireland', 'IRE, COR, Macroom'],
['Malbaie, Saguenay County, Canada East (Quebec), Canada', 'CAN, QC, Saguenay, La Malbaie'],
['Maryland, Maryland, USA', 'USA, MD'],
['Maryland, USA', 'USA, MD'],
['Massachusetts, United States of America', 'USA, MA'],
['Melrose, Roxburghshire, Scotland', 'SCO, ROX, Melrose'],
['Melsele, Oost-Vlaanderen, Belgium', 'BEL, EFL, Melsele'],
['Mevagissey, Cornwall, England', 'ENG, COR, Mevagissey'],
['Middlesex, England', 'ENG, MDL'],
['Middlesex, London, England', 'ENG, MDL'],
['Mijnsheerenland', 'NET, ZUI, Mijnsheerenland'],
['Mijnsheerenland, Binnenmaas, Zuid-Holland, Netherlands', 'NET, ZUI, Mijnsheerenland'],
['Mijnsheerenland, Zuid-Holland, Netherlands', 'NET, ZUI, Mijnsheerenland'],
['Mijnsheerenland, Zuid Holland, Netherlands', 'NET, ZUI, Mijnsheerenland'],
['Mijnsheerenland, Zuid-Holland, Pays-Bas', 'NET, ZUI, Mijnsheerenland'],
['Mijnsheerenland,Zuid-Holland, Netherlands', 'NET, ZUI, Mijnsheerenland'],
['Milford, Bucks, Pennsylvania, Colonial America', 'USA, PN, Pike, Milford'],
['Milford, Pike, Pennsylvania, United States', 'USA, PN, Pike, Milford'],
['Millbrook, Peterborough County, Ontario, Canada', 'CAN, ON, Peterborough, Millbrook'],
['Minneapolis, Hennepin Co., Minnesota, USA', 'USA, MN, Hennepin, Minneapolis'],
['Minneapolis, Hennepin, Minnesota, USA', 'USA, MN, Hennepin, Minneapolis'],
['Missoula, Missoula, Montana, USA', 'USA, MT, Missoula, Missoula'],
['Mobberly, Cheshire, England', 'ENG, CHS, Mobberly'],
['Monk Wearmouth, Durham, England', 'ENG, DUR, Monkwearmouth'],
['Monkwearmouth, Durham, England', 'ENG, DUR, Monkwearmouth'],
['Montgomery, Hamilton, Ohio, USA', 'USA, OH, Hamilton, Montgomery'],
['Monticello, Wright, Minnesota, USA', 'USA, MN, Wright, Monticello'],
['Murton, Northumberland, England', 'ENG, NBL, Murton'],
// ['M├╢rsfeld , Donnersbergkreis, Rhineland-Palatinate, Germany', 'GER, RP, Donnersbergkreis, Morsfeld'],
['Mörsfeld , Donnersbergkreis, Rhineland-Palatinate, Germany', 'GER, RP, Donnersbergkreis, Morsfeld'],
['Naaldwijk, Naaldwijk, Zuid-Holland, Pays-Bas', 'NET, ZUI, Naalswijk'],
['Naaldwijk, Zuid-Holland, Pays-Bas', 'NET, ZUI, Naalswijk'],
['Nailstone, Leicestershire, England', 'ENG, LEI, Nailstone'],
['Nelsonville, Athens, Ohio, USA', 'USA, OH, Athens, Nelsonville'],
['Nether Stowey, Somerset, England', 'ENG, SOM, Nether Stowey'],
['Netherlands', 'NET'],
['New Kent, British Colonial America, Virginia, USA', 'USA, VA, New Kent'],
['New York, New York, USA', 'USA, NY, New York'],
['New York, USA', 'USA, NY'],
['Newbold Verdon, Leicestershire, England', 'ENG, LEI, Newbold Verdon'],
['Newcastle, Northumberland, England', 'ENG, NBL, Newcastle'],
['Newton, Jasper, Iowa, USA', 'USA, IA, Jasper, Newton'],
['Nieuw-Beijerland', 'NET, ZUI, Nieuw-Beijerland'],
// ['Nordmyren farm, Hovin sokn, Ullensaker prestegjeld, Akershus, Norv├¿ge', 'NOR, AKR, Ullensaker prestegjeld, Hovin sokn, Nordmyren farm'],
['Nordmyren farm, Hovin sokn, Ullensaker prestegjeld, Akershus, Norvège', 'NOR, AKR, Ullensaker prestegjeld, Hovin sokn, Nordmyren farm'],
['North Petherton, Somerset, England', 'ENG, SOM, North Petherton'],
['Norway', 'NOR'],
['Nottingham, Nottinghamshire, England', 'ENG, NTT, Nottingham'],
['Numansdorp, Zuid-Holland, Netherlands', 'NET, ZUI, Numansdorp'],
['Numansdorp, Zuid-Holland, Pays-Bas', 'NET, ZUI, Numansdorp'],
// ['Nyg├Ñrden farm, ├àsnes, Hedmark, Norv├¿ge', 'NOR, HED, ├àsnes, Nyg├Ñrden farm'],
['Nygården farm, Åsnes, Hedmark, Norvège', 'NOR, HED, ├àsnes, Nyg├Ñrden farm'],
// ['N├ñsby, J├╢nk├╢ping, Sm├Ñland, Sverige', 'SWE, JON, Nasby'],
['Näsby, Jönköping, Småland, Sverige', 'SWE, JON, Nasby'],
['Ohio, USA', 'USA, OH'],
['Ohio, United States of America', 'USA, OH'],
['Oud Beierland, Zuid-Holland, Netherlands', 'NET, ZUI, Oud-Beijerland'],
['Oud Beijerland', 'NET, ZUI, Oud-Beijerland'],
['Oud-Beijerland, 6192, Zuid-Holland, Pays-Bas', 'NET, ZUI, Oud-Beijerland'],
['Oud-Beijerland, Beijerland, Zuid Holland, Netherlands', 'NET, ZUI, Oud-Beijerland'],
['Oud-Beijerland, Zuid-Holland, Netherlands', 'NET, ZUI, Oud-Beijerland'],
['Oud-Beijerland, Zuid-Holland, Pays-Bas', 'NET, ZUI, Oud-Beijerland'],
['Ouddorp, Goedereede, Zuid-Holland, Netherlands', 'NET, ZUI, Goedereede, Ouddorp'],
['Ouddorp, Goedereede, Zuid-Holland, Pays-Bas', 'NET, ZUI, Goedereede, Ouddorp'],
['Oxfordshire, England', 'ENG, OXF'],
['Peckleton, Leicestershire, England', 'ENG, LEI, Peckleton'],
['Pedmore, Worcester, Worcestershire, England', 'ENG, WOR, Worcester, Pedmore'],
['Pella, Marion, Iowa, USA', 'USA, IA, Marion, Pella'],
['Pennsylvania, Somerset, Pennsylvania, USA', 'USA, PN, Somerset'],
['Pennsylvania, USA', 'USA, PN'],
['Pennsylvania, United States of America', 'USA, PN'],
['Perrysburg, Miami, Indiana, USA', 'USA, IN, Miami, Perrysburg'],
['Perth, Towner, North Dakota, USA', 'USA, ND, Towner, Perth'],
['Pickering Grange, Leicestershire,  England', 'ENG, LEI, Pickering Grange'],
['Pike County, Ohio, USA', 'USA, OH, Pike'],
['Portsmouth, Newport, Rhode Island, USA', 'USA, RI, Newport, Portsmouth'],
['Powhatan, Powhatan, Virginia, USA', 'USA, VA, Powhatan, Powhatan'],
['Preble County, Ohio, USA', 'USA, OH, Preble'],
['Prestonsburg, Floyd, Kentucky, USA', 'USA, KY, Floyd, Prestonburg'],
// ['Qu├⌐bec, Canada', 'CAN, QC'],
['Québec, Canada', 'CAN, QC'],
['Reilsheim, Baden, Baden Wurttemberg, Allemagne', 'GER, BW, Baden, Reilsheim'],
['Renfrewshire, Scotland', 'SCO, RFW'],
['Ridderkerk, Zuid Holland, Netherlands', 'NET, ZUI, Ridderkerk'],
['Rijsoord, Ridderkerk, Zuid-Holland, Netherlands', 'NET, ZUI, Ridderkerk, Rijsoord'],
['Rock Hill, Bucks County, Pennsylvania, United States of America', 'USA, PN, Bucks, Rock Hill'],
['Rolde, Drenthe, Pays-Bas', 'NET, DRE, Rolde'],
['Rollete, North Dakota, USA', 'USA, ND, Rolette'],
['Rotterdam', 'NET, ZUI, Rotterdam'],
['Rotterdam, 6240, Zuid-Holland, Pays-Bas', 'NET, ZUI, Rotterdam'],
['Rotterdam, Zuid-Holland, Pays-Bas', 'NET, ZUI, Rotterdam'],
['Royalton, Windsor County, Vermont, United States of America', 'USA, VT, Windsor, Royalton'],
// ['Ruste 92, Hedalen, S├╕r-Aurdal, Oppland, Norv├¿ge', 'NOR, OPP, S├╕r-Aurdal, Hedalen, Ruste 92'],
['Ruste 92, Hedalen, Sør-Aurdal, Oppland, Norvège', 'NOR, OPP, Sør-Aurdal, Hedalen, Ruste 92'],
['Ruste, Hedal, Oppland, Norway', 'NOR, OPP, Hedal, Ruste'],
['Rye, East Sussex, England', 'ENG, SXE, Rye'],
['Saint Basile, Madawaska, New Brunswick, Canada', 'CAN, NB, Madawaska, St-Basile'],
['Saint Brunos Par.,Van Buren,Aroostook,Maine, USA', 'USA, ME, Aroostook, Van Buren, Saint Brunos Parish'],
['Saint Brunos Parish, Van Buren, Aroostook, Maine, USA', 'USA, ME, Aroostook, Van Buren, Saint Brunos Parish'],
['Saint John The Baptist,Chester,Cheshire,England', 'ENG, CHS, Chester, St John the Baptist'],
['Saint Margarets, Anne Arundel County, Maryland, USA', 'USA, MD, Anne Arundel, Saint Margarets'],
['Saint-Basile, Madawaska County, New Brunswick, Canada', 'CAN, NB, Madawaska, St-Basile'],
// ["Sainte-├ëlisabeth, D'Autray, Quebec, Canada", "CAN, QC, Lanaudiere, D'Autray, Sainte-Elisabeth"],
["Sainte-Élisabeth, D'Autray, Quebec, Canada", "CAN, QC, Lanaudiere, D'Autray, Sainte-Élisabeth"],
['Sandwich, Barnstable County, Massachusetts, USA', 'USA, MA, Barnstable, Sandwich'],
['Sandwich, Barnstable County, Massachusetts, United States of America', 'USA, MA, Barnstable, Sandwich'],
['Sandwich, Barnstable, MA, Massachusetts, USA', 'USA, MA, Barnstable, Sandwich'],
['Sandwich, Barnstable, MA, USA', 'USA, MA, Barnstable, Sandwich'],
['Sandwich, Barnstable, Massachusetts, USA', 'USA, MA, Barnstable, Sandwich'],
['Sandwich, Barnstable, Massachusetts, United States', 'USA, MA, Barnstable, Sandwich'],
['Scituate, Plymouth, Mass, Massachusetts, USA', 'USA, MA, Plymouth, Scituate'],
['Scituate, Plymouth, Massachusetts, United States', 'USA, MA, Plymouth, Scituate'],
['Scotch Block, Rolette, North Dakota, USA', 'USA, ND, Rolette, Scotch Block'],
['Scott, Virginia, United States', 'USA, VA, Scott'],
['Shenton, Leicestershire, England', 'ENG, LEI, Shenton'],
['Shepshed, Leicestershire, England', 'ENG, LEI, Shepshed'],
['Sint Anthoniepolder', 'NET, ZUI, Sint Anthoniepolder'],
['Sint Antonie Polder, South Holland, Netherlands', 'NET, ZUI, Sint Anthoniepolder'],
['Sint Antoniepolder, Zuid-Holland, Netherlands', 'NET, ZUI, Sint Anthoniepolder'],
['Somerset County, Maryland, USA', 'USA, MD, Somerset'],
['Somerset County, Maryland, United States of America', 'USA, MD, Somerset'],
['Somerset, Maryland, USA', 'USA, MD, Somerset'],
['Somerset, Montgomery, Maryland, USA', 'USA, MD, Montgomery, Somerset'],
['Somerset, Pennsylvania, USA', 'USA, PN, Somerset'],
['Somerset, Somerset, Pennsylvania, United States', 'USA, PN, Somerset, Somerset'],
["St Ann's, Dublin, Leinster, Ireland", "IRE, DUB, St Ann's"],
['St Basile, Madawaska, New Brunswick, Canada', 'CAN, NB, Madawaska, St-Basile'],
['St Joachim, Chateaugay, Quebec, Canada', 'CAN, QC, La Côte-de-Beaupré, St Joachim'],
['St Marys, Somerset, England', 'ENG, SOM, St Marys'],
['St Paul, Joliette, Quebec, Canada', 'CAN, QC, Lanaudiere, Joliette, St Paul'],
['St Sepulchre Newgate, London, England', 'ENG, LND, Newgate, St Sepulchre'],
['St Sepulchre, Newgate, London, London, England', 'ENG, LND, Newgate, St Sepulchre'],
// ['St-Ambroise-de-Kildare, Joliette, Qu├⌐bec, Canada', 'CAN, QC, Lanaudiere, Joliette, St-Ambroise-de-Kildare'],
['St-Ambroise-de-Kildare, Joliette, Québec, Canada', 'CAN, QC, Lanaudiere, Joliette, St-Ambroise-de-Kildare'],
['St-Basile, Madawaska, New Brunswick, Canada', 'CAN, NB, Madawaska, St-Basile'],
// ["St-Jacques-de-l'Achigan, (Moncalm), Qu├⌐bec, Canada", "CAN, QC, Lanaudiere, St. Jacques l'Achigan"],
["St-Jacques-de-l'Achigan, (Moncalm), Québec, Canada", "CAN, QC, Lanaudiere, St. Jacques l'Achigan"],
// ['St-Louis, Kamouraska, Qu├⌐bec, Canada', 'CAN, QC, Bas-Saint-Laurent, Kamouraska, St-Louis'],
['St-Louis, Kamouraska, Québec, Canada', 'CAN, QC, Bas-Saint-Laurent, Kamouraska, St-Louis'],
['St-Roches-des-Aulnais, Quebec, Canada', 'CAN, QC, Chaudiere-Appalaches, St-Roches-des-Aulnais'],
["St. Jacques l'Achigan, Quebec, Canada", "CAN, QC, Lanaudiere, St. Jacques l'Achigan"],
['Stanhope, Durham, England', 'ENG, DUR, Stanhope'],
['Stark County, Ohio, USA', 'USA, OH, Stark'],
['Ste Martine, Chateaugay, Quebec, Canada', 'CAN, QC, Monteregie, Chateaugay, Sainte-Martine '],
['Stepney Parish, Middlesex, , England', 'ENG, MDL, Stepney Parish'],
['Stirlingshire, Scotland', 'SCO, STI'],
['Stonington, New London County, Connecticut, USA', 'USA, CT, New London, Stonington'],
['Strassburg,Lorraine,Bas Rhin,Alsace,France', 'FRA, ALS, Strassburg'],
['Stratford Bow, Middlesex, England', 'ENG, MDL, Stratford Bow'],
['Strijen, Zuid-Holland, Netherlands', 'NET, ZUI, Strijen'],
['Strijen, Zuid-Holland, Pays-Bas', 'NET, ZUI, Strijen'],
['Strongs Prairie Twp, Adams, Wisconsin, USA', 'USA, WI, Adams, Strongs Prairie Township'],
// ['Str├Ñngan├ñs  V├ñsterg├Ñrd, ├älmeboda, Kronoberg, Sverige', 'SWE, KRO, ├älmeboda, Str├Ñngan├ñs V├ñsterg├Ñrd'],
['Strånganäs  Västergård, Älmeboda, Kronoberg, Sverige', 'SWE, KRO, Älmeboda, Västergård, Strånganäs'],
// ['Str├Ñngan├ñs ├älmeboda, Kronoberg, Sverige', 'SWE, KRO, ├älmeboda, Str├Ñngan├ñs'],
['Strånganäs Älmeboda, Kronoberg, Sverige', 'SWE, KRO, Älmeboda, Strånganäs'],
['Surry, North Carolina, USA', 'USA, NC, Surrey'],
['Sutton Cheney, Leicestershire, England', 'ENG, LEI, Sutton Cheney'],
['Swansea, Bristol County, Massachusetts, United States of America', 'USA, MA, Bristol, Swansea'],
['Swansea, Bristol, Massachusetts, USA', 'USA, MA, Bristol, Swansea'],
['Sweden', 'SWE'],
['Symondsbury, Dorset, England', 'ENG, DOR, Symondsbury'],
['Thames River Valley, Essex, England', 'ENG, ESS, Thames River Valley'],
['Thornton, Leicestershire, England', 'ENG, LEI, Thornton'],
['Thorpe Underwood, Kettering, Northamptonshire, England', 'ENG, NOR, Kettering, Thorpe Underwood'],
['To, Oppland, Norway', 'NOR, OPP, To'],
['Torquay, Devon, England', 'ENG, DEV, Torquay'],
['Torr, Devon, England', 'ENG, DEV, Torr'],
['Trimble Township, Athens, Ohio, USA', 'USA, OH, Athens, Trimble Township'],
// ['Ullensaker, Akershus, Norv├¿ge', 'NOR, AKR, Ullensaker'],
['Ullensaker, Akershus, Norway', 'NOR, AKR, Ullensaker'],
['Ullensaker, Akershus, Norvège', 'NOR, AKR, Ullensaker'],
['VA, Virginia, USA', 'USA, VA'],
['Valeria, Jasper County, Iowa, USA', 'USA, IA, Jasper, Valeria'],
['Van Buren, Aroostook, Maine, United States', 'USA, ME, Aroostook, Van Buren'],
['Vermillion, LaSalle, Illinois, USA', 'USA, IL, LaSalle, Vermillion'],
// ['Vieboda S├╢derg├Ñrd, Linneryd, Kronoberg, Sverige', 'SWE, KRO, Linneryd, Vieboda S├╢derg├Ñrd'],
['Vieboda Södergård, Linneryd, Kronoberg, Sverige', 'SWE, KRO, Linneryd, Vieboda Södergård'],
['Virginia British Colony, Virginia, USA', 'USA, VA'],
['Virginia, USA', 'USA, VA'],
['Voluntown, New London County, Connecticut, United States of America', 'USA, CT, New London, Voluntown'],
// ['V├ñstra Skyberg, V├ñrmland, Sverige', 'SWE, VAR, V├ñstra Skyberg'],
['Västra Skyberg, Värmland, Sverige', 'SWE, VAR, Västra Skyberg'],
['Wachtebrke, Oost-Vlaanderen, Belgique', 'BEL, EFL, Wachtebrke'],
['Walker, Northumberland, England', 'ENG, NBL, Walker'],
['Warrentown, Fauquier, VA, Virginia, USA', 'USA, VA, Fauquier, Warrentown'],
['Washington, Pennsylvania, USA', 'USA, PN, Washington'],
['Washington, Virginia, USA', 'USA, VA, Washington'],
['West Chester, Chester, Pennsylvania', 'USA, PN, Chester, West Chester'],
['Westerly, Washington, Rhode Island, USA', 'USA, RI, Washington, Westerly'],
['Westhorpe, Suffolk, England', 'ENG, SFK, Westhorpe'],
['Westmaas, Beijerland, Zuid-Holland, Netherlands', 'NET, ZUI, Westmaas, Beijerland'],
['Westmaas, Binnenmaas Municipality, Zuid-Holland, Netherlands', 'NET, ZUI, Westmass, Binnenmaas'],
['Westmaas, Cromstrijen, Zuid-Holland, Netherlands', 'NET, ZUI, Westmaas, Cromstrijen'],
['Westmaas, South Holland, Netherlands', 'NET, ZUI, Westmaas'],
['Westmaas, Zuid-Holland, Pays-Bas', 'NET, ZUI, Westmaas'],
['Weymouth, Dorset, England', 'ENG, DOR, Weymouth'],
['What Cheer, Keokuk, Iowa, USA', 'USA, IA, Keokuk, What Cheer'],
['Winchester, Frederick, Maryland, USA', 'USA, MD, Frederick, Winchester'],
['Wixhausen, Darmstadt, Starkenburg, Hessen, Germany', 'GER, HE, Starkenberg, Darmstadt, Wixhausen'],
['Woodsboro, Frederick, Maryland, USA', 'USA, MD, Frederick, Woodsboro'],
['Yarmouth, Barnstable County, Massachusetts, United States of America', 'USA, MA, Barnstable, Yarmouth'],
['Zweibrucken, Rhineland-Palatinate, Allemagne', 'GER, RP, Zweibrucken'],
['defaulted, New York, USA', 'USA, NY'],
['melrose, Kirkcudbrightshire, Scotland', 'SCO, KKD, Melrose'],
// ['n├╕rre F├╕nhus 56/2, H├╕lera, S├╕r-Aurdal, Oppland, NorSør-Aurdalv├¿ge', 'NOR, OPP, S├╕r-Aurdal, H├╕lera, n├╕rre F├╕nhus 56/2'],
['nørre Fønhus 56/2, Hølera, Sør-Aurdal, Oppland, Norvège', 'NOR, OPP, Sør-Aurdal, Hølera, Nørre Fønhus 56/2'],
['presumed, Devon, England', 'ENG, DEV'],
['presumed, Durham, England', 'ENG, DUR'],
['presumed, Edinburgh, Midlothian, Scotland', 'SCO, MLN, Edinburgh'],
['presumed, Linlithgowshire, Scotland', 'SCO, WLN'],
['presumed, New York, USA', 'USA, NY'],
['presumed, Northumberland, England', 'ENG, NBL'],
['presumed, Pennsylvania, USA', 'USA, PN'],
['presumed, Renfrewshire, Scotland', 'SCO, RFW'],
['presumed, Yorkshire, ENgland', 'ENG, YKS'],
['presumed, Zuid-Holland, Pays-Bas', 'NET, ZUI'],
['stepney parish, Wicomico County, Maryland, USA', 'USA, MD, Wimico, Stepney Parish'],
// ['├älmeboda fg, Lekram├Ñla, Kronoberg, Su├¿de', 'SWE. KRO, Lekram├Ñla, ├älmeboda fg'],
['Älmeboda fg, Lekramåla, Kronoberg, Suède', 'SWE, KRO, Lekramåla, Älmeboda fg'],
// ['├älmeboda, Kronoberg, Sweden', 'SWE, KRO, ├älmeboda'],
['Älmeboda, Kronoberg, Sweden', 'SWE, KRO, Älmeboda'],
// ['├àsli farm, S├╕r-Aurdal, Oppland, Norv├¿ge', 'NOR, OPP, S├╕r-Aurdal, ├àsli farm', "NOR, OPP, S├╕r-Aurdal, ├àsli farm"],
['Åsli farm, Sør-Aurdal, Oppland, Norvège', 'NOR, OPP, S├╕r-Aurdal, ├àsli farm', "NOR, OPP, Sør-Aurdal, Åsli farm"],
// ['├àsnes ├ÿstre, ├àsnes, Hedmark, Norv├¿ge', 'NOR, HED, Asnes, ├àsnes ├ÿstre', 'NOR, HED, ├àsnes, ├àsnes ├ÿstre'],
['Åsnes Østre, Åsnes, Hedmark, Norvège', 'NOR, HED, Asnes, ├àsnes ├ÿstre', 'NOR, HED, Åsnes, Åsnes Østre'],
])
