export { createManifest, logItems, logPages, ignore, newpg, recto, same, verso } from './createManifest.js'
export { default as Book } from './Book.svelte'
export { default as Date } from './Date.svelte'
export { default as Enquote } from './Enquote.svelte'
export { default as H1 } from './h1.svelte'
export { default as H2 } from './h2.svelte'
export { default as H3 } from './h3.svelte'
export { default as H4 } from './h4.svelte'
export { default as ManifestTable } from './ManfiestTable.svelte'
export { default as Name } from './Name.svelte'
export { default as NewPage } from './NewPage.svelte'
export { default as P } from './P.svelte'
export { default as Place } from './Place.svelte'
export { default as SectionContent } from './SectionContent.svelte'
export { default as SectionPlaceholder } from './SectionPlaceholder.svelte'
export { default as SectionTitle } from './SectionTitle.svelte'
export { default as Source } from './Source.svelte'

export { default as Pager } from './Pager.svelte'
export { setup } from './setup.js'